spring.application.name=file_upload

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB

spring.file-upload-path=src/main/resources/files

# application.properties
rustfs.url=http://localhost:9000
rustfs.access.name=${RUSTFS_ACCESS_KEY}
rustfs.access.secret=${RUSTFS_SECRET_KEY}
rustfs.bucket.name=demo-file-upload